#!/bin/bash
declare -g -A channel_users channels

h_rpl_namreply () {
    local name
    shift 3
    if [[ $1 == [\@\*\=] ]]; then
        local chan_visibility=$1
        shift
    fi
    local chan=${1,,}
    shift
    if [[ -z $getting_namreply ]]; then
        getting_namreply=1
        declare -g -A channel_users=()
    fi
    for name in $@; do
        local flag=
        [[ ${ircd_features['prefix:1']} =~ ${name:0:1} ]] &&
            flag=${name:0:1} name=${name:1}
        channel_users["$chan"]+="$name "
    done
}
add_handler '353' h_rpl_namreply

h_rpl_endofnames () {
    unset getting_namreply
}
add_handler '366' h_rpl_endofnames

h_join () {
    local chan=${3,,} who=$(split_hostmask "$2")
    who=${who,,}
    if [[ $who == ${nick,,} ]]; then
        channels["$chan"]=1
    fi
}
add_handler join h_join

h_part () {
    local chan=${3,,} who=$(split_hostmask "$2")
    who=${who,,}
    if [[ $who == ${nick,,} ]]; then
        unset channels["$chan"]
        unset channel_users["$chan"]
    else
        channel_users["$chan"]=$(del_list "$who" ${channel_users[@]})
    fi
}
add_handler part h_part
return 0
