#!/bin/bash

# Reload the DemonBot core and reload all scripts.
reload_core () {
    IFS=$' \t\n\r'
    oifs=$IFS
    local dir
    if is_exec _unload_core; then
        log -c 'Running core unload.'
        $"_unload_core"
    fi
    log 'Reloading core and all scripts.'
    log_only=1
    local script reload_scripts=("${!loaded_scripts[@]}") opt_s=1
    unload_all_scripts
    del_all_handlers
    del_all_commands
    del_all_connectors
    . "$0"
    unset opt_s
    for s in "${reload_scripts[@]}"; do
        [[ $s =~ ':' ]] && continue
        load_script "$s"
    done
    unset log_only
    log "The core has been reloaded successfully."
    return 0
}

