#!/bin/bash

syntax () {
    local i=0
    while (($# > 0)); do
        ((++i))
        if [[ ! $1 =~ $3 ]]; then
            local a=$1
            [[ $a ]] && a="'$a'"
            echo "You screwed up the $2 in argument #$i; you put ${a:-nothing} where I expected /$3/."
            return 1
        fi
        shift 3
    done
    return 0
}

