#!/bin/bash

# Unload all scripts that have been sourced by `source_all` or `load_script`.
unload_all_scripts () {
    local script
    for script in "${!loaded_scripts[@]}"; do
        [[ $script =~ ':' ]] && continue
        unload_script "$script"
    done
}

