#!/bin/bash

# List currently-loaded scripts.
#
# Output:
#   script_name script_filee registered_funcs
script_list () {
    for k in "${!loaded_scripts[@]}"; do
        [[ $k =~ ':' ]] && continue
        echo "$k (${loaded_scripts["$k"]##*/})" \
            "[${loaded_scripts["$k:funcs"]:0:-1}]"
    done | sort
}

