#!/bin/bash

# Determine whether a user is in the specified group(s) by arguments.
# If no groups are specified, the 'global' group will be assumed.
#
# Parameters:
#   [group ...]
# Exit Codes:
#   0   User is in one or more of specified groups.
#   1   User is not in any of the specified groups.
check_clearance () {
    groups='global'
    [[ -z $sender || -z $sender_mask ]] && return 1
    local group
    identify_user && groups="users ${users["$sender_mask:groups"]}"
    [[ -z $1 ]] && set -- 'global'
    for group in $groups; do
        in_list "$group" 'root' "$@" &&
            return 0
    done
    return 1
}

