#!/bin/bash

c_useradd () {
    local name home
    if [[ $origin == $sender ]]; then
        if is_user "$1"; then
            log 'Someone else is already using that name.'
            return 1
        elif check_clearance admin; then
            update_user "$@"
        else
            update_user "$1" "$2"
        fi
        if [[ $? == 0 ]]; then
            log "User added successfully."
        else
            log "There was a problem adding the user to the database."
        fi
    else
        log "Why are you trying to set this in the channel?! Send me a query! And don't use the same password!"
    fi
}
add_command useradd c_useradd

