#!/bin/bash

c_passwd () {
    local name home
    if [[ $origin == $sender ]]; then
        if ! identify_user; then
            log "I can't figure out which user you are. Identify yourself."
            return 1
        fi
        local key=$(sha1sum <<< "$1" | cut -d' ' -f1)
        local correct_key=$(<"$home/login-key")
        if [[ $key != $correct_key ]]; then
            log "Incorrect old password."
            return 1
        fi
        update_user "$name" "$2"
        log "Your password has been updated."
    else
        log "Why are you trying to set this in the channel?! Send me a query! And don't use the same password!"
    fi
}
add_command passwd c_passwd global

