#!/bin/bash

c_identify () {
    local name home
    if [[ $origin == $sender ]]; then
        if ! is_user "$1"; then
            log "Incorrect username or password."
            return 1
        fi
        local key=$(sha1sum <<< "$2" | cut -d' ' -f1)
        local correct_key=$(<"$home/login-key")
        if [[ $key != $correct_key ]]; then
            log "Incorrect username or password."
            return 1
        fi
        add_user_mask "$name" "$sender_mask"
        if identify_user "$name"; then
            log "Hello, $name. You have been successfully identified."
            return 0
        else
            log "You could not be identified."
            return 1
        fi
    else
        log "You're not supposed to tell me this in the channel! Send me a query next time!"
        if is_user "$1"; then
            local key=$(sha1sum <<< "$2" | cut -d' ' -f1)
            local correct_key=$(<"$home/login-key")
            local new_pass=$(cat /dev/urandom | tr -dc '[:alnum:]' | head -c50)
            if [[ $key == $correct_key ]]; then
                update_user "$1" "$new_pass"
                whisper
                log "I changed your password to: $new_pass"
                log "After you identify, change this with: passwd $new_pass NEW_PASSWORD"
            else
                log "The password was incorrect. You should change it after you identify. Preferably right now."
            fi
        fi
    fi
}
add_command identify c_identify

