#!/bin/bash

c_userdel () {
    local name=${1,,} home
    if ! check_clearance admin && [[ $name != ${sender,,} ]]; then
        log "You're not powerful enough. You can only delete yourself."
        return 1
    elif ! is_user "$name"; then
        log "I do not have a user named $name."
        return 1
    fi
    rm -rf "$home/$name"
    log "User deleted."
}
add_command useradd c_useradd admin

