#!/bin/bash

# Read the list of known users from the known users savefile.
#
# Return Codes:
#   0   Users read successfully
#   1   No known users
load_users () {
    log -c 'Parsing users file.'
    users=()
    if [[ ! -f "$users_file" ]]; then
        log 'No users known.'
        return 1
    fi
    local h data
    while read -r h data; do
        [[ $data ]] && users["$h"]=$data
    done < "$users_file"
    log -c 'Read list of known users from disk.'
}

