#!/bin/bash

# Add a new hostmask to a user's trusted hostmask list.
#
# Parameters:
#   username mask [mask ...]
add_user_mask () {
    local name home
    if ! is_user "$1"; then
        log -c "No such user: $name"
        return 1
    fi
    shift
    printf '%s\n' "$@" >> "$home/masks"
    sort -u "$home/masks" > "$home/masks.new"
    mv "$home/masks.new" "$home/masks"
    return 0
}

