#!/bin/bash

# Create or update user password and group information.
#
# Parameters:
#   username password [group ...]
update_user () {
    local name home
    if ! is_user "$1"; then
        log -c "Creating user directory: $home"
        mkdir -p "$home"
    fi
    log -c "Setting password."
    sha1sum <<< "$2" | cut -d' ' -f1 > "$home/login-key"
    shift 2
    if [[ $1 ]]; then
        log -c "Setting groups."
        printf '%s\n' "$@" > "$home/groups"
    fi
    return 0
}

