#!/bin/bash

# Write the list of known users from to known users savefile.
#
# Return Codes:
#   0   Savefile written successfully
#   1   Error while writing savefile
save_users () {
    log -c 'Writing users file.'
    local h
    for h in "${!users[@]}"; do
        echo $h ${users["$h"]}
    done > "$users_file" || return 1
    log -c 'Wrote list of known users to disk.'
}

