#!/bin/bash

c_groupdel () {
    local name home
    if ! is_user "$1"; then
        log "I do not have a user named $name."
        return 1
    fi
    shift
    grep -vFf <(printf '%s\n' "$@") "$home/groups" > "$home/groups.new"
    mv "$home/groups.new" "$home/groups"
    log "User removed from groups."
}
add_command groupdel c_groupdel admin

