#!/bin/bash

# Connect to an IRC server and punt IRC messages.to a parser loop.
# stdout: 9<>$demonbot_out
# stderr: sent to logger as debug messages
#
# Uses Globals:
#   host
#   [port]
#   [connector]
connect () {
    while $next_host; do
        if [[ -z $host ]]; then
            log -c 'Missing host.'
            return 1
        fi
        port=${port:-6667}
        connector=${connector:-tcp}
        con_bin=${connectors["$connector"]}
        unset logged_in user_disconnect
        rm -f "$demonbot_out" 2>/dev/null
        mkfifo "$demonbot_out"
        exec 9<&-
        exec 9<>"$demonbot_out"
        connection >&9 2> >(read_do log -d) &
        connection_pid=$!
        parser_loop <&9
        unset connection_pid
        exec 9<&-
        safe_kill HUP
        [[ $user_disconnect || $reconnect_auto < 1 ]] && break
        if [[ $hosts ]]; then
            log -c "Waiting $reconnect_secs seconds to reconnect."
            sleep $reconnect_secs
        fi
    done
}

