#!/bin/bash

# Send command to IRC server.
#
# Parameters:
#   command data
send () {
    local IFS=' '
    if [[ -p "$demonpit_in" ]]; then
        if [[ ${1:0:1} != ':' ]]; then
            echo "${1^^} ${*:2}" >&8
        else
            echo "$1 ${2^^} ${*:3}" >&8
        fi
    else
        log -c 'Not connected to server.'
        return 1
    fi
}

